### ISSUE TITLE
simplify `ModelViewSet` subclassing

### ISSUE THREAD

**Issue by fabiocaccamo** [hbakri/django-ninja-crud#216]
If a `ModelViewSet` implements all the operations using the same In/Out schemas, the following class:
```python
class DepartmentViewSet(ModelViewSet):
    model_class = Department

    # AbstractModelView subclasses can be used as-is
    list = ListModelView(output_schema=DepartmentOut)
    create = CreateModelView(input_schema=DepartmentIn, output_schema=DepartmentOut)
    retrieve = RetrieveModelView(output_schema=DepartmentOut)
    update = UpdateModelView(input_schema=DepartmentIn, output_schema=DepartmentOut)
    delete = DeleteModelView()
```

could be declared simply like that:

```python
class DepartmentViewSet(ModelViewSet):
    model_class = Department
    output_schema = DepartmentOut
    input_schema = DepartmentIn
```

**Comment by hbakri** [comment]
Hello @fabiocaccamo !

Firstly, thank you so much for your interest in `Django Ninja CRUD` and for the star! ✨

Your suggestion about simplifying the declaration of `ModelViewSet` is insightful. I understand the appeal of a more concise syntax, especially for those familiar with Django Rest Framework's `ModelViewSet`.

### **Why It's Designed The Way It Is**

The current design intentionally emphasizes composition and modularity for `ModelViews`. This was designed to be explicit and granular to allow the most flexibility. Each CRUD operation (List, Create, Retrieve, Update, Delete) can be customized independently. This granularity allows developers to define exactly what they need, which sometimes may not be the entire set of CRUD operations.

### **What We Could Do**

Your idea aligns well with some thoughts I've had recently to introduce a new class that simplifies this for the common case where all CRUD operations are used with the same In/Out schemas. Such a class could be an excellent addition for users who don't need to customize the CRUD operations heavily.

I've been considering names like `CRUDModelViewSet` or `LCRUDModelViewSet` for this new feature. I'm still contemplating the best approach and naming, so if you have any thoughts, they'd be much appreciated!

Thank you once again for your insightful comment. Contributions like yours are what help improve this project, making it easier and more efficient for everyone.

**Comment by fabiocaccamo** [comment]
@hbakri I would only make the current class more flexible, in this way it would be possible to customise only some operations, all the others fallback to the default behaviour using the default schema.

**Comment by hbakri** [comment]
@fabiocaccamo Thank you for your continued interest and for taking the time to share your ideas on how to improve the library. I have considered your latest suggestions and I'd like to provide you with an updated perspective on the direction we are thinking of taking.

### Enhancing `ModelViewSet`'s Flexibility
Firstly, your point about making `ModelViewSet` more flexible without compromising its explicit nature resonates with me. One way we could achieve this is by introducing a `default_input_schema` and `default_output_schema` at the class level. This would allow you to optionally omit the schema attributes in each of the views if they align with the default. So, something like this would be possible:

```python
class DepartmentViewSet(ModelViewSet):
    model_class = Department
    default_input_schema = DepartmentIn
    default_output_schema = DepartmentOut

    list = ListModelView()
    create = CreateModelView()
    retrieve = RetrieveModelView()
    update = UpdateModelView()
    delete = DeleteModelView()
```

This maintains the explicitness and granularity that are core to the philosophy of Django Ninja CRUD while reducing redundancy where possible.

### Introducing `BaseModelViewSet`
That said, your suggestion has also inspired me to introduce a new class called `BaseModelViewSet`. This class is intended to provide a simplified, more concise syntax but specifically for the most straightforward CRUD operations that utilize the same In/Out schemas.

Here's how you could define a set of CRUD views using `BaseModelViewSet`:

```python
class DepartmentViewSet(BaseModelViewSet):
    model_class = Department
    input_schema = DepartmentIn
    output_schema = DepartmentOut
```

With `BaseModelViewSet`, you'll be able to accomplish similar functionality to `ModelViewSet`, but in a more condensed manner specifically for basic CRUD operations. This will allow developers to choose the level of granularity and explicitness that best suits their needs.

I'm excited about what these new features are going to bring to the Django Ninja CRUD community. Please continue to share your thoughts and ideas.

**Comment by hbakri** [comment]
@fabiocaccamo I'm thrilled to hear that you find the proposed solution excellent! Thank you for your very quick response; your input has been invaluable.

I'm planning to include these updates in the next major release, which will likely be version `v0.4.0`. The tentative release date for this is around the end of September. Please note that this is a tentative timeline and subject to change, primarily because there's a substantial amount of documentation to be written, especially concerning the testing tools of the package. Nonetheless, I'll do my best to stick to the timeline!

**Comment by fabiocaccamo** [comment]
Thank you in advance for the next release!
