### ISSUE TITLE
how to handle `ForeignKey` relations ?

### ISSUE THREAD

**Issue by Yacobolo** [hbakri/django-ninja-crud#240]
Currently im looking into using the pre_save hook on create:

```python
def set_job_type_and_status(request, instance) -> None:
    job_type_id = getattr(instance, 'job_type_id', None)
    job_status_id = getattr(instance, 'job_status_id', None)

    if job_type_id:
        instance.job_type = JobType.objects.get(id=job_type_id)
    if job_status_id:
        instance.job_status = JobStatus.objects.get(id=job_status_id)
```

Is this the best approach or do you have any other reccomendation?

**Comment by Yacobolo** [comment]
Hi again, i created a pre_save hook to fix it all automatically. Maybe you could get inspired to implement this feature in your code?

### model_utils.py
```python
from typing import List, Optional
from django.core.exceptions import FieldError
from django.shortcuts import get_object_or_404
from django.db import models
from django.db.models import Model


def set_created_updated_by(request, instance: 'Model', action: str) -> None:
    """
    Set 'created_by' and 'updated_by' fields based on the action.
    """
    user = request.user
    if action == 'update':
        instance.updated_by = user
    else:
        instance.created_by = user



def set_foreign_keys(instance: Model, field_names: List[str]) -> None:
    """
    Dynamically set foreign keys on the instance based on provided field names.
    """
    for field_name in field_names:
        # Ensure the field is a ForeignKey
        field = instance._meta.get_field(field_name)
        if not isinstance(field, models.ForeignKey):
            raise FieldError(f"'{field_name}' is not a ForeignKey on {instance.__class__.__name__}")

        # Fetch the related model instance and set it
        related_model_id = getattr(instance, f"{field_name}_id", None)
        if related_model_id:
            related_model_class = field.related_model
            related_instance = get_object_or_404(related_model_class, id=related_model_id)
            setattr(instance, field_name, related_instance)



def pre_save_hook(field_names: Optional[List[str]] = None):
    """
    Return a pre-save function to set 'created_by', 'updated_by', and foreign keys.
    """
    def pre_save(request, create_instance, update_instance=None) -> None:
        instance = update_instance or create_instance
        action = 'update' if update_instance else 'create'
        set_created_updated_by(request, instance, action)
        if field_names:
            set_foreign_keys(instance, field_names)
    return pre_save
```

then it can simply be imported and applied like this:
### job_view.py
```python
class JobViewSet(ModelViewSet):
    model_class = Job

    # AbstractModelView subclasses can be used as-is
    list = ListModelView(output_schema=JobOut)
    create = CreateModelView(
        input_schema=JobIn,
        output_schema=JobOut,
        pre_save=pre_save_hook(['job_type', 'job_status']),
    )
    retrieve = RetrieveModelView(output_schema=JobOut)
    update = UpdateModelView(
        input_schema=JobIn,
        output_schema=JobOut,
        pre_save=pre_save_hook(['job_type', 'job_status']),
    )
    delete = SoftDeleteModelView()
```

**Comment by hbakri** [comment]
Hi @Yacobolo, thank you for diving deep into `django-ninja-crud`!

Upon reviewing the `set_job_type_and_status` hook, you're spot on. The function, in its current form, doesn't provide any additional value. By design, Django automatically manages the relationship between `{field_name}` and `{field_name}_id`. Assigning a value to `{field_name}_id` implicitly sets up the relationship without any further intervention. So, the hook you provided essentially reassigns the ID values that are already set.

You can safely remove this hook and only keep the `created_by` and `updated_by` logics, and Django will handle the foreign key relationships smoothly ! 🙌

**Comment by Yacobolo** [comment]
Thank you, Hicham! This makes sense. It seems I had done a bit of overengineering.

**Explanation for Others:**  
To explain simply to others who might be interested:

1. **In my Job model:**  
   I defined `job_status` as follows:
   ```python
   job_status = models.ForeignKey(JobStatus, on_delete=models.DO_NOTHING)
   ```

2. **In my JobIn schema:**  
   I added:
   ```python
   job_status_id: int
   ```

3. **Final Step:**  
   Ensure that a job status exists with the specified ID. After this, everything worked seamlessly using the `ModelViewSet`.

**Comment by hbakri** [comment]
Your welcome Jacob! You don't even have to check the existence of the `ForeignKey` field thanks to the [`full_clean()`](https://docs.djangoproject.com/en/4.2/ref/models/instances/#django.db.models.Model.full_clean) method that is called just before the [`save()`](https://docs.djangoproject.com/en/4.2/ref/models/instances/#django.db.models.Model.save) in both the **Update** (cf. [views/update.py](https://github.com/hbakri/django-ninja-crud/blob/main/ninja_crud/views/update.py#L99-L100)) and **Create** (cf. [views/create.py](https://github.com/hbakri/django-ninja-crud/blob/main/ninja_crud/views/create.py#L178-L179)) operations 🙌

When specifying an inexistent object, a [`ValidationError`](https://docs.djangoproject.com/en/4.2/ref/exceptions/#django.core.exceptions.ValidationError) is going to be raised and catch by the exception handler you defined [here](https://github.com/hbakri/django-ninja-crud/wiki/03-Setup) and then a 400 Bad Request is sent with a clear message and description. ✨

**Comment by Yacobolo** [comment]
Fancy!
