### ISSUE TITLE
Add `guides` for `authentication`

### ISSUE THREAD

**Issue by hbakri** [hbakri/django-ninja-crud#342]

**Comment by faridelnasire** [comment]
Following; would love to know how to best handle this! :)

**Comment by hbakri** [comment]
Hi @faridelnasire, I'm excited to share some core insights on handling authentication and authorization using `django-ninja-crud`! 🤸‍♀️

### Authentication
For **global authentication**, `django-ninja-crud` works seamlessly with the standard Django Ninja approach (cf. [documentation](https://django-ninja.dev/guides/authentication/)). Here’s a quick refresher:
```python
# Global authentication example
from ninja import Router
from ninja.security import HttpBearer
from ninja_crud import views, viewsets

# ... Import your models, schemas ...

class GlobalAuth(HttpBearer):
    def authenticate(self, request, token):
        if token == "supersecret":
            return token

router = Router(auth=GlobalAuth())

class DepartmentViewSet(viewsets.ModelViewSet):
    model = Department

    list_departments = views.ListModelView(
        output_schema=DepartmentOut
    )
    # ... other views ...
```

But things get even more interesting when you want **specific endpoint authentication**. Thanks to @lucasrcezimbra's fantastic work in PR #93, you can directly pass arguments to the router for each view. This means you can have different authentication mechanisms for different endpoints:

```python
# Specific endpoint authentication example
from ninja import Router
from ninja.security import HttpBearer
from ninja_crud import views, viewsets

# ... Import your models, schemas ...

class SpecificAuth(HttpBearer):
    def authenticate(self, request, token):
        if token == "supersecret":
            return token

router = Router()

class DepartmentViewSet(viewsets.ModelViewSet):
    model = Department

    list_departments = views.ListModelView(
        output_schema=DepartmentOut, 
        router_kwargs={"auth": SpecificAuth()}
    )
    # ... other views ...
```

### Authorization
Now, onto the meatier topic of **authorization**, particularly tailored to your business logic. The key here lies in using **decorators** imo. Here’s an example of how you can restrict access based on your business rules:

```python
# Example of using decorators for authorization
from functools import wraps
from django.core.exceptions import PermissionDenied
from ninja import Router

# ... Import your models, schemas ...

def user_is_creator(func):
    @wraps(func)
    def wrapper(request, *args, **kwargs):
        department_id = kwargs.get("id")
        department = Department.objects.get(id=department_id)
        if department.created_by != request.auth:
            raise PermissionDenied()
        return func(request, *args, **kwargs)

    return wrapper

class DepartmentViewSet(viewsets.ModelViewSet):
    model = Department

    update_department = views.UpdateModelView(
        input_schema=DepartmentIn,
        output_schema=DepartmentOut,
        decorators=[user_is_creator],
    )
    delete_department = views.DeleteModelView(decorators=[user_is_creator])
    # ... other views ...
```

In this example, the `user_is_creator` decorator can be used to ensure that only the creators of an object can modify or delete it.

I'm currently working on a comprehensive article that will delve deeper into these topics. Your questions and suggestions are invaluable and will help make the content as helpful and informative as possible. If you have any specific scenarios or challenges you'd like me to cover, feel free to share!

Stay tuned, and thanks for your interest and engagement! 🙌
