### ISSUE TITLE
Request for built-in default `Exception` handlers

### ISSUE THREAD

**Issue by Ramin-RX7** [hbakri/django-ninja-crud#385]
In different views, when trying to retrieve an object with an id that does not exist in the database, we will face an Internal Server Error which causes 5xx http code/error. Instead we can use a code similar to this to check whether the object exists or not.

```python
qs = model_class.objects.filter(pk=id)
if qs.exists():
  # OK
else:
  # handle the not found query
```

As far as I'm concerned, this happens in `RetrieveModelView`, `UpdateModelView` and `DeleteModelView`.

Since I was not sure how this needs to be handled (what json schema to return to user) I did not work on it myself and let you decide how it must be implemented

**Comment by hbakri** [comment]
Hi @Ramin-RX7, thank you for pointing this out! The approach you suggested is _valid_, but I've designed the package to allow users to define **custom** exception handling for flexibility. This is why in the [setup documentation](https://django-ninja-crud.readme.io/docs/03-setup), I recommend defining an [exception handler](https://django-ninja.dev/guides/errors/) for `ObjectDoesNotExist`:

```python
@api.exception_handler(ObjectDoesNotExist)
def handle_object_does_not_exist(request, exc):
    return api.create_response(
        request,
        {"message": "ObjectDoesNotExist", "detail": str(exc)},
        status=HTTPStatus.NOT_FOUND,
    )
```

This way, users can decide on their own JSON response format, ensuring consistent and uniform error handling across all endpoints, including those outside of CRUD operations. This consistency is harder to maintain with direct approaches like the one you mentioned, where error handling is embedded within each view. 

I'm still open to suggestions and might consider integrating a more direct approach in future updates. Thank you for your feedback! ✨

**Comment by Ramin-RX7** [comment]
Hey @hbakri, Thank you for your response. I haven't gone through your library completely. Not yet. But it just keeps getting even more interesting for me. 
What you have made looks cool and clean I gotta say. I still think there's way to improve the method we have (for exception handling) as of now.
If it would be possible to create JSON schemes and have them as an attribute to our views might be a good approach too. First checking if the error handling is possible within view itself or not. Then checking the `api` object.
I would like to know your opinion about this too. 
Right now I'm busy but I would like to get more involved in this library and show my opinions with code and help in development of it in near future.

**Comment by hbakri** [comment]
Hi @Ramin-RX7, I'm closing this issue because in the upcoming `v0.5.0` release, the tests are no longer tied to the views. This means users can define their own exception handlers as needed. While I understand the importance of good practices in exception handling, I believe that defining implicit default error handlers within views can be misleading and limit customizability, so I'll provide examples in the documentation instead in order to guide users on best practices for exception handling.

Once again, thank you for your input, and I invite you to check the new testing package by the way https://github.com/hbakri/django-rest-testing if you have any feedback! 🌻

**Comment by Ramin-RX7** [comment]
Hey @hbakri . Thanks for checking this issue again after few months. 

> defining implicit default error handlers within views can be misleading and limit customizability

I do not totally agree with you on this but this seems much reasonable. 

Also I will check the repo you suggested which might be really helpful. Thanks
