### ISSUE TITLE
中文用户有福了

### ISSUE THREAD

**Issue by horizon365** [hbakri/django-ninja-crud#423]
Is your feature request related to a problem? Please describe.
[中文用户有福了，手敲原汁原味中文文档上线，无广告。](https://django-ninja.cn/django-ninja-crud/)

Describe the solution you'd like
纯中文文档，无广告干扰。 https://django-ninja.cn/django-ninja-crud/

包含 django-ninja， django-ninja-jwt，django-ninja-crud ， django-ninja-extra [全系列的中文文档](https://django-ninja.cn/)。

**Comment by hbakri** [comment]
Hi @horizon365! Thank you for sharing this Chinese documentation link. I'm going to add it to the README under "International Documentation" like this:

```markdown
## 🌎 International Documentation

- [中文文档](https://django-ninja.cn/django-ninja-crud/) (Chinese Documentation - Community Contributed)

Note: Community-contributed translations may not always reflect the latest updates.
```

Appreciate your contribution to making Django Ninja CRUD more accessible! 🙏
